apiVersion: v1
kind: ConfigMap
metadata:
  name: keda-kafka-configmap
  namespace: default
data:
  brokers: "192.168.88.207:29092"
  request-topic: "request-topic"
  response-topic: "response-topic"
  error-topic: "error-topic"
